# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/mnt/d/Portable Workstation/file exchange/PSPOD"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/mnt/d/Portable Workstation/file exchange/PSPOD"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/d/Portable Workstation/file exchange/PSPOD/CMakeFiles" "/mnt/d/Portable Workstation/file exchange/PSPOD/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/d/Portable Workstation/file exchange/PSPOD/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PSPOD

# Build rule for target.
PSPOD: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PSPOD
.PHONY : PSPOD

# fast build rule for target.
PSPOD/fast:
	$(MAKE) -f CMakeFiles/PSPOD.dir/build.make CMakeFiles/PSPOD.dir/build
.PHONY : PSPOD/fast

src/PSPOD.o: src/PSPOD.cpp.o

.PHONY : src/PSPOD.o

# target to build an object file
src/PSPOD.cpp.o:
	$(MAKE) -f CMakeFiles/PSPOD.dir/build.make CMakeFiles/PSPOD.dir/src/PSPOD.cpp.o
.PHONY : src/PSPOD.cpp.o

src/PSPOD.i: src/PSPOD.cpp.i

.PHONY : src/PSPOD.i

# target to preprocess a source file
src/PSPOD.cpp.i:
	$(MAKE) -f CMakeFiles/PSPOD.dir/build.make CMakeFiles/PSPOD.dir/src/PSPOD.cpp.i
.PHONY : src/PSPOD.cpp.i

src/PSPOD.s: src/PSPOD.cpp.s

.PHONY : src/PSPOD.s

# target to generate assembly for a file
src/PSPOD.cpp.s:
	$(MAKE) -f CMakeFiles/PSPOD.dir/build.make CMakeFiles/PSPOD.dir/src/PSPOD.cpp.s
.PHONY : src/PSPOD.cpp.s

src/global.o: src/global.cpp.o

.PHONY : src/global.o

# target to build an object file
src/global.cpp.o:
	$(MAKE) -f CMakeFiles/PSPOD.dir/build.make CMakeFiles/PSPOD.dir/src/global.cpp.o
.PHONY : src/global.cpp.o

src/global.i: src/global.cpp.i

.PHONY : src/global.i

# target to preprocess a source file
src/global.cpp.i:
	$(MAKE) -f CMakeFiles/PSPOD.dir/build.make CMakeFiles/PSPOD.dir/src/global.cpp.i
.PHONY : src/global.cpp.i

src/global.s: src/global.cpp.s

.PHONY : src/global.s

# target to generate assembly for a file
src/global.cpp.s:
	$(MAKE) -f CMakeFiles/PSPOD.dir/build.make CMakeFiles/PSPOD.dir/src/global.cpp.s
.PHONY : src/global.cpp.s

src/input.o: src/input.cpp.o

.PHONY : src/input.o

# target to build an object file
src/input.cpp.o:
	$(MAKE) -f CMakeFiles/PSPOD.dir/build.make CMakeFiles/PSPOD.dir/src/input.cpp.o
.PHONY : src/input.cpp.o

src/input.i: src/input.cpp.i

.PHONY : src/input.i

# target to preprocess a source file
src/input.cpp.i:
	$(MAKE) -f CMakeFiles/PSPOD.dir/build.make CMakeFiles/PSPOD.dir/src/input.cpp.i
.PHONY : src/input.cpp.i

src/input.s: src/input.cpp.s

.PHONY : src/input.s

# target to generate assembly for a file
src/input.cpp.s:
	$(MAKE) -f CMakeFiles/PSPOD.dir/build.make CMakeFiles/PSPOD.dir/src/input.cpp.s
.PHONY : src/input.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... PSPOD"
	@echo "... edit_cache"
	@echo "... src/PSPOD.o"
	@echo "... src/PSPOD.i"
	@echo "... src/PSPOD.s"
	@echo "... src/global.o"
	@echo "... src/global.i"
	@echo "... src/global.s"
	@echo "... src/input.o"
	@echo "... src/input.i"
	@echo "... src/input.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

